Repository ideacrew/enroll, pull requests merged in 2021-05, with the labels that each got.

#286 93495
  components/financial_assistance/app/models/financial_assistance/applicant.rb
  components/financial_assistance/app/views/financial_assistance/benefits/_esi_benefit.html.erb
  components/financial_assistance/app/views/financial_assistance/benefits/_esi_benefit_form.html.erb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#240 89519
  components/financial_assistance/app/assets/javascripts/financial_assistance/deduction.js
  components/financial_assistance/app/assets/javascripts/financial_assistance/income.js
  components/financial_assistance/app/controllers/financial_assistance/applicants_controller.rb
  components/financial_assistance/app/views/financial_assistance/incomes/other.html.erb
  features/financial_assistance/income_adjustments_page.feature
  features/financial_assistance/job_income.feature
  features/financial_assistance/other_income_page.feature
  features/financial_assistance/step_definitions/income_adjustments_page_steps.rb
  features/financial_assistance/step_definitions/other_income_page_steps.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#315 94285
  script/update_eligibility_94651.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#343 94954
  app/models/unassisted_plan_cost_decorator.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#325 92324
  app/models/factories/enrollment_factory.rb
  app/models/person.rb
  spec/controllers/employers/census_employees_controller_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Support

#207 93317
  app/helpers/insured/families_helper.rb
  features/employee/employee_with_future_doh.feature
  spec/helpers/insured/families_helper_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#345 94998
  app/controllers/concerns/config/contact_center_concern.rb
  app/controllers/employers/census_employees_controller.rb
  app/models/census_employee.rb
  app/views/employers/census_employees/_initiate_cobra.html.erb
  features/employers/cobra.feature
  features/employers/step_definitions/cobra_steps.rb
  features/step_definitions/employers_steps.rb
  spec/controllers/employers/census_employees_controller_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#353 95047
  app/data_migrations/cobra_census_employee_fix_may_2021.rb
  lib/tasks/migrations/cobra_census_employee_fix_may_2021.rake
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Stakeholder Review, Tracker: Data

#282 93364
  components/financial_assistance/app/models/financial_assistance/application.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#92 92039
  config/client_config/dc/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  script/shop_sep_query.rb
  spec/script/shop_sep_query_spec.rb
  system/config/templates/features/aca_shop_market/aca_shop_market.yml
Labels: Mergeable: No, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#346 94694
  app/models/census_employee.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#365 95088
  app/data_migrations/cobra_census_employee_fix_may_2021.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Data

#340 94546
  app/domain/operations/people/create_or_update.rb
  components/financial_assistance/app/views/financial_assistance/applicants/_edit.html.erb
  spec/domain/operations/people/create_or_update_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#378 95284
  components/benefit_markets/spec/dummy/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/benefit_markets/spec/dummy/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/benefit_markets/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/benefit_markets/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/benefit_sponsors/spec/dummy/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/benefit_sponsors/spec/dummy/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/benefit_sponsors/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/benefit_sponsors/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/financial_assistance/spec/dummy/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/financial_assistance/spec/dummy/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/financial_assistance/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/financial_assistance/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/notifier/spec/dummy/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/notifier/spec/dummy/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/notifier/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/notifier/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/sponsored_benefits/spec/dummy/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/sponsored_benefits/spec/dummy/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/sponsored_benefits/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/sponsored_benefits/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/transport_gateway/spec/dummy/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/transport_gateway/spec/dummy/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/transport_gateway/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/transport_gateway/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/transport_profiles/spec/dummy/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/transport_profiles/spec/dummy/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/transport_profiles/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/transport_profiles/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/ui_helpers/spec/dummy/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/ui_helpers/spec/dummy/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/ui_helpers/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  components/ui_helpers/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  config/client_config/dc/system/config/templates/features/aca_individual_market/aca_individual_market.yml
  system/config/templates/features/aca_individual_market/aca_individual_market.yml
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#375 93469
  components/financial_assistance/app/helpers/financial_assistance/application_helper.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug
