Repository ideacrew/enroll, pull requests merged in 2021-08, with the labels that each got.

#547 94228
  components/financial_assistance/app/assets/javascripts/financial_assistance/income.js
Labels: Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support, Mergeable: Yes

#580 95769
  app/models/forms/family_member.rb
Labels: Status: Accepted Pending Release, Mergeable: Yes, Priority: 4-Normal, Tracker: Bug

#568 95486
  components/financial_assistance/app/helpers/financial_assistance/application_helper.rb
Labels: Priority: 1-Immediate, Status: Accepted Pending Release, Mergeable: Yes, Tracker: Bug
