Repository ideacrew/enroll, pull requests merged in 2021-03, with the labels that each got.

#30 92829
  app/controllers/insured/family_members_controller.rb
  spec/controllers/insured/family_members_controller_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Final Security Review (DevOps), Tracker: Support

#93 91784
  app/domain/operations/individual/cancel_renewal_enrollment.rb
  app/models/hbx_enrollment.rb
  components/benefit_sponsors/spec/dummy/app/models/hbx_enrollment.rb
  spec/models/hbx_enrollment_spec.rb
Labels: Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#94 91016
  app/models/forms/bulk_actions_for_admin.rb
  spec/controllers/exchanges/hbx_profiles_controller_spec.rb
  spec/models/forms/bulk_actions_for_admin_spec.rb
Labels: Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#59 92800
  app/views/insured/families/_enrollment.html.erb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#36 92736
  app/models/hbx_enrollment.rb
  app/views/insured/families/_enrollment.html.erb
  spec/models/hbx_enrollment_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Support

#83 92828
  components/financial_assistance/app/assets/stylesheets/financial_assistance/financial_assistance.scss
  components/financial_assistance/app/models/financial_assistance/forms/applicant.rb
  components/financial_assistance/app/views/financial_assistance/applications/review_and_submit.html.erb
  components/financial_assistance/app/views/financial_assistance/applications/steps.yml
  components/financial_assistance/spec/models/financial_assistance/forms/applicant_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Support

#119 93159
  app/models/census_employee.rb
  spec/models/census_employee_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#127 93077
  components/financial_assistance/app/models/financial_assistance/application.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Promote to Test Environment, Tracker: Code Refactor

#134 92821
  app/views/shared/person/_consumer_information.html.erb
  app/views/shared/person/_personal_information.html.erb
  components/financial_assistance/app/views/financial_assistance/applicants/_edit.html.erb
  features/financial_assistance/family_info.feature
  features/financial_assistance/step_definitions/family_info_steps.rb
  features/insured/individual_dependent_address.feature
  features/step_definitions/individual_steps.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Promote to Test Environment, Tracker: Bug

#123 93200
  components/financial_assistance/app/domain/financial_assistance/operations/application/request_determination.rb
  components/financial_assistance/lib/schemas/individual.xsd
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#165 93343
  app/assets/stylesheets/insured.scss.erb
  components/financial_assistance/app/views/financial_assistance/applications/index.html.erb
  components/financial_assistance/app/views/financial_assistance/applications/raw_application.html.erb
  components/financial_assistance/app/views/financial_assistance/applications/steps.yml
  components/financial_assistance/app/views/financial_assistance/incomes/other.html.erb
  features/financial_assistance/raw_application.feature
  features/financial_assistance/step_definitions/financial_assistance_steps.rb
  features/support/worlds/ivl_assistance_world.rb
Labels: Assignee: Vishal Kalletla, Mergeable: Yes, Priority: 3-High, Status: Peer Review, Tracker: Support

#151 93077
  components/financial_assistance/app/models/financial_assistance/application.rb
Labels: Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Code Refactor

#168 92571
  components/financial_assistance/app/models/financial_assistance/forms/applicant.rb
Labels: Assignee: Utkarsh Shukla, Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Bug

#176 92746
  components/financial_assistance/app/views/financial_assistance/shared/_fa_left_nav.html.erb
Labels: Assignee: Utkarsh Shukla, Mergeable: Yes, Priority: 3-High, Status: Promote to Test Environment, Tracker: Support

#156 93363
  components/financial_assistance/app/controllers/financial_assistance/applications_controller.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#149 92821
  app/views/shared/person/_consumer_information.html.erb
  app/views/shared/person/_personal_information.html.erb
  components/financial_assistance/app/views/financial_assistance/applicants/_edit.html.erb
  features/financial_assistance/family_info.feature
  features/financial_assistance/step_definitions/family_info_steps.rb
  features/insured/individual_dependent_address.feature
  features/step_definitions/individual_steps.rb
Labels: Assignee: NOT ASSIGNED, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#164 93272
  app/domain/validators/families/applicant_contract.rb
  app/domain/validators/families/determination_contract.rb
  spec/domain/validators/families/applicant_contract_spec.rb
  spec/domain/validators/families/determination_contract_spec.rb
Labels: Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#184 93300
  app/models/coverage_household.rb
  spec/models/coverage_household_spec.rb
Labels: Assignee: Utkarsh Shukla, Mergeable: Yes, Priority: 1-Immediate, Status: Promote to Test Environment, Tracker: Bug

#197 93029
  components/financial_assistance/app/models/financial_assistance/applicant.rb
  components/financial_assistance/app/views/financial_assistance/applicants/other_questions.html.erb
  components/financial_assistance/spec/controllers/financial_assistance/applicants_controller_spec.rb
  features/financial_assistance/step_definitions/other_questions_page_steps.rb
Labels: Priority: 1-Immediate, Status: Peer Review, Tracker: App-Dev_Use Case

#214 93496
  system/config/templates/features/aca_individual_market/aca_individual_market.yml
Labels: Assignee: Alex Thomas, Mergeable: Yes, Priority: 1-Immediate, Status: Functional Testing, Tracker: Data

#215 93500
  system/config/templates/features/enroll_app/enroll_app.yml
Labels: Assignee: Kathlin Nicol, Mergeable: Yes, Priority: 1-Immediate, Status: Stakeholder Review, Tracker: Support
