Repository ideacrew/enroll, pull requests merged in 2021-06, with the labels that each got.

#389 95259
  components/benefit_sponsors/app/models/benefit_sponsors/services/new_profile_registration_service.rb
Labels: Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#393 95396
  components/financial_assistance/app/views/financial_assistance/deductions/index.html.erb
  features/financial_assistance/step_definitions/income_adjustments_page_steps.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#382 95118
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/general_agency_profiles/_index.html.erb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Support

#398 95342
  components/financial_assistance/app/views/financial_assistance/applications/eligibility_results.html.erb
  components/financial_assistance/db/seedfiles/translations/en/faa_translations.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#341 93896
  components/financial_assistance/app/models/financial_assistance/applicant.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#222 93509
  components/financial_assistance/app/views/financial_assistance/applications/index.html.erb
  components/financial_assistance/db/seedfiles/translations/en/faa_translations.rb
  features/financial_assistance/cost_savings.feature
  features/financial_assistance/raw_application.feature
  features/financial_assistance/start_new_application.feature
  features/financial_assistance/step_definitions/fa_not_applying.rb
  features/financial_assistance/step_definitions/financial_assistance_steps.rb
  features/step_definitions/individual_steps.rb
  features/support/worlds/ivl_assistance_world.rb
Labels: Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#295 93514
  app/data_migrations/financial_assistance/change_application_state.rb
  components/financial_assistance/app/helpers/financial_assistance/application_helper.rb
  components/financial_assistance/app/models/financial_assistance/application.rb
  components/financial_assistance/app/views/financial_assistance/applications/index.html.erb
  features/financial_assistance/cost_savings.feature
  features/financial_assistance/review_applications.feature
  features/financial_assistance/step_definitions/view_eligibility_steps.rb
  features/financial_assistance/view_eligibility.feature
  features/support/object_model_pages/financial_assistance/cost_savings_application_page.rb
  lib/tasks/migrations/financial_assistance/change_application_state.rake
  spec/lib/tasks/migrations/financial_assistance/change_application_state_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#428 95496
  components/financial_assistance/app/models/financial_assistance/applicant.rb
  components/financial_assistance/spec/models/financial_assistance/applicant_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Support
