Repository ideacrew/enroll, pull requests merged in 2021-04, with the labels that each got.

#27 92712
  app/controllers/insured/group_selection_controller.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#225 93367
  app/models/effective/datatables/employee_datatable.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Support

#146 93081
  app/models/census_employee.rb
  spec/models/census_employee_spec.rb
Labels: Assignee: Kathryn Sullivan, Mergeable: Yes, Priority: 2-Urgent, Status: Stakeholder Review, Tracker: Bug

#161 92867
  app/assets/javascripts/plan_shopping.js.erb
  app/domain/operations/individual/calculate_monthly_aggregate.rb
  app/helpers/hbx_admin_helper.rb
  app/models/admin/aptc.rb
  app/models/eligibility_determination.rb
  app/models/factories/ivl_eligibility_factory.rb
  app/models/hbx_enrollment.rb
  app/views/hbx_admin/_enrollment_header.html.erb
  app/views/insured/plan_shoppings/show.html.slim
  app/views/ui-components/v1/filters/_plan_filters.html.slim
  features/admin/admin_sep_selection.feature
  features/group_selection/dual_role_plan_shopping.feature
  features/insured/individual_assisted_signup.feature
  features/insured/individual_dependent_address.feature
  features/insured/individual_immigration_details_failure.feature.broken
  features/insured/individual_immigration_details_success.feature
  features/insured/individual_verification.feature
  features/insured/individual_vlp_verification.feature
  features/step_definitions/individual_steps.rb
  features/step_definitions/phone_application_steps.rb
  features/support/object_model_pages/ivl/faa/ivl_faa_family_information.rb
  features/support/object_model_pages/ivl/faa/ivl_faa_help_paying_for_coverage.rb
  features/support/object_model_pages/ivl/homepage/ivl_homepage.rb
  features/support/object_model_pages/ivl/registration/ivl_authorization_and_consent.rb
  features/support/object_model_pages/ivl/registration/ivl_choose_coverage.rb
  features/support/object_model_pages/ivl/registration/ivl_choose_plan.rb
  features/support/object_model_pages/ivl/registration/ivl_enrollment_submitted.rb
  features/support/object_model_pages/ivl/registration/ivl_personal_information.rb
  features/support/object_model_pages/ivl/registration/ivl_verify_identity.rb
  features/support/object_model_pages/your_information.rb
  spec/domain/operations/individual/calculate_monthly_aggregate_spec.rb
  spec/helpers/hbx_admin_helper_spec.rb
  spec/models/eligibility_determination_spec.rb
  spec/models/factories/eligibility_factory_spec.rb
  spec/models/tax_household_spec.rb
  system/config/templates/features/aca_individual_market/aca_individual_market.yml
Labels: Assignee: Kathlin Nicol, Priority: 4-Normal, Status: Stakeholder Review, Tracker: Epic (Master Ticket)

#227 89736
  components/financial_assistance/app/views/financial_assistance/applicants/other_questions.html.erb
  features/financial_assistance/other_questions_page.feature
  features/financial_assistance/step_definitions/other_questions_page_steps.rb
  features/financial_assistance/step_definitions/submit_your_application_steps.rb
  features/step_definitions/household_info_continue_button_steps.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#230 93458
  app/assets/javascripts/demographics_fields.js
  components/financial_assistance/app/views/financial_assistance/applicants/_dependent_form.html.erb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#233 92818
  components/financial_assistance/app/views/financial_assistance/shared/support_text.yml
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#281 94327
  components/financial_assistance/app/views/financial_assistance/applications/steps.yml
  components/ui_helpers/lib/ui_helpers/workflow_helper.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#284 94290
  app/models/forms/family_member.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug
