Repository ideacrew/enroll, pull requests merged in 2021-12, with the labels that each got.

#1395 enable dr notice for Maine for testing purposes only
  config/client_config/me/system/config/templates/features/enroll_app/enroll_app.yml
Labels: config-change

#1382 fix erroneously assigned county values
  lib/tasks/fix_maine_nil_counties.rake
  spec/lib/tasks/fix_maine_nil_counties_spec.rb
Labels: script

#1460 Fix `SelfTermOrCancelForm` spec
  spec/models/insured/forms/self_term_or_cancel_form_spec.rb
Labels: date-based-failure
