Repository ideacrew/enroll, pull requests merged in 2025-09, with the labels that each got.

#5642 add logging for new applying coverage change in consumer role subscriber
  app/domain/operations/consumer_roles/on_update.rb
  spec/domain/operations/consumer_roles/on_update_spec.rb
Labels: bugfix

#5641 update state transition events
  app/models/eligibilities/v3/evidence_utils.rb
  spec/models/eligibilities/v3/evidence_utils_spec.rb
Labels: bugfix, cr-120+

#5657 revert ai/an value should not be dependent on citizen_status
  app/models/person.rb
  spec/models/person_spec_1.rb
Labels: bugfix, cr-120+

#5652 remove update option for admin(imported apps)
  app/helpers/dropdown_helper.rb
  spec/helpers/dropdown_helper_spec.rb
Labels: bugfix

#5653 single quotes on current application page and add missing word
  app/views/insured/sbm/applications/current_applications.html.erb
  db/seedfiles/translations/en/me/insured.rb
Labels: bugfix, cr-120+

#5646 fix alien number pre 1957 disclaimer text on fa
  components/financial_assistance/app/views/financial_assistance/applicants/docs_shared/_alien_number.html.erb
  components/financial_assistance/app/views/financial_assistance/shared/_citizenship_cert_fields.html.erb
  components/financial_assistance/app/views/financial_assistance/shared/_naturalization_cert_fields.html.erb
  features/financial_assistance/create_applicant_bs4.feature
  features/financial_assistance/step_definitions/applicant_personal_info_page_steps.rb
  features/support/object_model_pages/financial_assistance/applicant_form.rb
Labels: bugfix

#5664 fix phone number display issue
  app/views/shared/_phone_fields.html.erb
  features/financial_assistance/step_definitions/applicant_personal_info_page_steps.rb
  features/insured/individual_manage_family.feature
  features/insured/step_definitions/individual_steps.rb
Labels: bugfix

#5637 modify oeg oeq trigger
  app/domain/operations/hbx_enrollments/determine_oe_notice_recipients.rb
  script/oeg_oeq_notice_triggers.rb
  spec/domain/operations/hbx_enrollments/determine_oe_notice_recipients_spec.rb
Labels: enhancement, cr-120+

#5622 fix application selection for medicaid pdm bulk script
  components/financial_assistance/app/domain/financial_assistance/operations/applications/medicaid_gateway/run_periodic_data_matching.rb
  components/financial_assistance/spec/domain/financial_assistance/operations/applications/medicaid_gateway/run_periodic_data_matching_spec.rb
Labels: bugfix

#5691 build family determination for ssavlp after evidence update
  app/domain/operations/eligibilities/v3/individual_market/ssa_vlp_determined.rb
Labels: bugfix, cr-120+

#5674 align negative response dmi processing
  app/event_source/subscribers/enrollment_subscriber.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/esi/h14/add_esi_mec_determination.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/ifsv/h9t/ifsv_eligibility_determination.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/medicaid_gateway/add_mec_check_application.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/non_esi/h31/add_non_esi_mec_determination.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/rrv/ifsv/add_rrv_ifsv_determination.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/rrv/medicare/add_rrv_medicare_determination.rb
  components/financial_assistance/spec/domain/financial_assistance/operations/applications/esi/add_esi_mec_determination_spec.rb
  components/financial_assistance/spec/domain/financial_assistance/operations/applications/ifsv/h9t/ifsv_eligibility_determination_spec.rb
  components/financial_assistance/spec/domain/financial_assistance/operations/applications/medicaid_gateway/add_mec_check_application_spec.rb
  components/financial_assistance/spec/domain/financial_assistance/operations/applications/non_esi/add_non_esi_mec_determination_spec.rb
  components/financial_assistance/spec/domain/financial_assistance/operations/applications/rrv/ifsv/add_rrv_ifsv_determination_spec.rb
  components/financial_assistance/spec/domain/financial_assistance/operations/applications/rrv/medicare/add_rrv_medicare_determination_spec.rb
Labels: bugfix

#5704 upgrade rexml to 4.4.4
  .docker/config/Gemfile
  Gemfile
  Gemfile.lock
  components/benefit_markets/Gemfile.lock
  components/benefit_markets/benefit_markets.gemspec
  components/benefit_sponsors/Gemfile.lock
  components/benefit_sponsors/benefit_sponsors.gemspec
  components/financial_assistance/Gemfile.lock
  components/financial_assistance/financial_assistance.gemspec
  components/notifier/Gemfile.lock
  components/notifier/notifier.gemspec
  components/sponsored_benefits/Gemfile.lock
  components/sponsored_benefits/sponsored_benefits.gemspec
  components/transport_gateway/Gemfile.lock
  components/transport_gateway/transport_gateway.gemspec
  components/transport_profiles/Gemfile.lock
  components/transport_profiles/transport_profiles.gemspec
Labels: chore

#5662 add eligibility determination related cucumbers
  app/assets/javascripts/qhp_application.js
  app/helpers/application_helper.rb
  app/views/insured/individual_market/applicants/_form.html.erb
  app/views/insured/individual_market/applicants/index.html.erb
  app/views/insured/individual_market/applications/eligibility_results.html.erb
  app/views/insured/sbm/applications/_application_card.html.erb
  app/views/insured/sbm/applications/current_applications.html.erb
  features/financial_assistance/add_new_member.feature
  features/financial_assistance/create_applicant_bs4.feature
  features/financial_assistance/step_definitions/applicant_level_navigation_steps.rb
  features/financial_assistance/step_definitions/applicant_personal_info_page_steps.rb
  features/financial_assistance/step_definitions/family_info_steps.rb
  features/individual_market/add_member.feature
  features/individual_market/edit_member.feature
  features/individual_market/eligibility_determination.feature
  features/individual_market/step_definitions/edit_member_steps.rb
  features/individual_market/step_definitions/eligibility_determination_steps.rb
  features/individual_market/step_definitions/individual_market_steps.rb
  features/individual_market/step_definitions/qhp_application_form_steps.rb
  features/individual_market/step_definitions/qhp_application_navigation_steps.rb
  features/individual_market/step_definitions/qhp_application_setup_steps.rb
  features/step_definitions/household_info_continue_button_steps.rb
  features/step_definitions/individual_steps.rb
  features/support/object_model_pages/individual_market/applicant_form.rb
  features/support/object_model_pages/ivl/iap/ivl_iap_family_information.rb
  features/support/object_model_pages/ivl/qhp/ivl_qhp_common_elements.rb
  features/support/object_model_pages/ivl/qhp/ivl_qhp_current_applications_page.rb
  features/support/object_model_pages/ivl/qhp/ivl_qhp_eligibility_results_page.rb
  features/support/object_model_pages/ivl/qhp/ivl_qhp_submit_page.rb
  features/support/worlds/individual_market/individual_market_world.rb
  spec/factories/users.rb
Labels: enhancement, cr-120+

#5720 fetch prev evidence state
  app/models/eligibilities/v3/evidence_utils.rb
  spec/domain/operations/eligibilities/v3/individual_market/ssa_vlp_determined_spec.rb
  spec/models/eligibilities/v3/evidence_utils_spec.rb
Labels: bugfix, cr-120+

#5719 correctly format payloads with a colon in a field body
  app/helpers/application_helper.rb
  spec/helpers/application_helper_spec.rb
Labels: bugfix, cr-120+

#5738 pass right param for determined oustanding
  app/models/eligibilities/v3/evidence_utils.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/esi/h14/add_esi_mec_determination.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/ifsv/h9t/ifsv_eligibility_determination.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/non_esi/h31/add_non_esi_mec_determination.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/pvc/non_esi_evidence/determine_and_store_response.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/rrv/income_evidence/determine_and_store_response.rb
  components/financial_assistance/app/domain/financial_assistance/operations/applications/rrv/non_esi_evidence/determine_and_store_response.rb
Labels: bugfix, cr-120+

#5715 add spousal filing validation
  components/financial_assistance/app/controllers/financial_assistance/applications_controller.rb
  components/financial_assistance/app/helpers/financial_assistance/application_helper.rb
  components/financial_assistance/app/models/financial_assistance/applicant.rb
  components/financial_assistance/app/models/financial_assistance/application.rb
  components/financial_assistance/app/views/financial_assistance/applicants/_applicants.html.erb
  components/financial_assistance/app/views/financial_assistance/applicants/_applicants_income_and_coverage_info.html.erb
  components/financial_assistance/app/views/financial_assistance/applicants/_applicants_info.html.erb
  components/financial_assistance/app/views/financial_assistance/applicants/_dependent_applicant.html.erb
  components/financial_assistance/app/views/financial_assistance/applicants/_dependent_applicant_income_and_coverage_info.html.erb
  components/financial_assistance/app/views/financial_assistance/applicants/tax_info.html.erb
  components/financial_assistance/app/views/financial_assistance/applications/_fa_table.html.erb
  components/financial_assistance/app/views/financial_assistance/applications/_financial_assistance_row.html.erb
  components/financial_assistance/app/views/financial_assistance/applications/edit.html.erb
  components/financial_assistance/app/views/financial_assistance/applications/review_and_submit.html.erb
  components/financial_assistance/app/views/financial_assistance/shared/_fa_left_nav.html.erb
  components/financial_assistance/app/views/financial_assistance/shared/_info_needed.html.erb
  components/financial_assistance/db/seedfiles/translations/en/dc/financial_assistance.rb
  components/financial_assistance/db/seedfiles/translations/en/me/financial_assistance.rb
  components/financial_assistance/spec/models/financial_assistance/applicant_spec.rb
  components/financial_assistance/spec/models/financial_assistance/application_spec.rb
  config/client_config/dc/system/config/templates/features/aca_individual_market/financial_assistance.yml
  config/client_config/me/system/config/templates/features/aca_individual_market/financial_assistance.yml
  features/financial_assistance/family_info_bs4.feature
  features/financial_assistance/step_definitions/family_info_steps.rb
  features/financial_assistance/step_definitions/other_questions_page_steps.rb
  features/financial_assistance/step_definitions/tax_info_steps.rb
  features/financial_assistance/tax_info_bs4.feature
  features/step_definitions/household_info_continue_button_steps.rb
  system/config/templates/features/aca_individual_market/financial_assistance.yml
Labels: enhancement

#5737 redirect to eligibilities evidence path on verifications document delete
  app/controllers/eligibilities/evidences/documents_controller.rb
  spec/controllers/eligibilities/evidences/documents_controller_spec.rb
Labels: bugfix, cr-120+
