Repository ideacrew/enroll, pull requests merged in 2025-07, with the labels that each got.

#5375 allow admins to update ssns via applications
  app/helpers/application_helper.rb
  app/models/presenters/ssn_form_presenter.rb
  spec/models/presenters/ssn_form_presenter_spec.rb
Labels: cr-120+

#5387 notify keycloak of changes to user mobile phone records.
  Gemfile.lock
  app/domain/entities/identity_providers.rb
  app/domain/entities/identity_providers/user_contact_information.rb
  app/domain/entities/identity_providers/user_information.rb
  app/domain/operations/people/handle_phone_changed.rb
  app/event_source/events/user_account_information/contact_numbers_updated.rb
  app/event_source/publishers/user_account_information_publisher.rb
  app/models/phone.rb
  spec/event_source/events/user_account_information/contact_numbers_updated_spec.rb
Labels: enhancement

#5405 log out links/buttons should trigger leaving modal
  app/javascript/controllers/leaving_modal_controller.js
Labels: cr-120+

#5294 qhp family info page bug fixes
  app/helpers/application_helper.rb
  app/javascript/controllers/applicant_controller.js
  app/javascript/controllers/family_information_controller.js
  app/models/presenters/ssn_form_presenter.rb
  app/views/insured/consumer_roles/docs_shared/_visa_number.html.erb
  app/views/insured/individual_market/applicants/_form.html.erb
  app/views/insured/individual_market/applicants/_immigration_document_templates.html.erb
  spec/models/presenters/ssn_form_presenter_spec.rb
Labels: cr-120+

#5421 use count instead of size for identity verification script
  app/domain/operations/people/validate_identity_verification.rb
Labels: bugfix

#5422 fix placement of not sure link on qhp applicant form
  app/views/insured/individual_market/applicants/_form.html.erb
Labels: cr-120+

#5420 modal leave button fixes and auto opening of applicant form cross application
  app/javascript/controllers/leaving_modal_controller.js
  app/models/individual_market/applicant.rb
  app/views/insured/individual_market/applicants/_form.html.erb
  app/views/insured/individual_market/applicants/_summary.html.erb
  app/views/insured/individual_market/applicants/index.html.erb
Labels: cr-120+

#5427 allow admins to update SSN and display error message if no ssn is entered
  app/assets/javascripts/financial_assistance.js
  app/helpers/application_helper.rb
  app/models/forms/consumer_candidate.rb
  app/views/insured/family_members/_dependent_form.html.erb
  app/views/insured/individual_market/applicants/_form.html.erb
  components/financial_assistance/app/controllers/financial_assistance/applicants_controller.rb
  components/financial_assistance/app/domain/financial_assistance/validators/applicant_contract.rb
  components/financial_assistance/app/models/financial_assistance/forms/applicant.rb
  components/financial_assistance/app/views/financial_assistance/applicants/_edit.html.erb
  components/financial_assistance/spec/controllers/financial_assistance/applicants_controller_spec.rb
  components/financial_assistance/spec/domain/financial_assistance/validators/applicant_contract_spec.rb
  components/financial_assistance/spec/models/financial_assistance/forms/applicant_spec.rb
  db/seedfiles/translations/en/dc/insured.rb
  db/seedfiles/translations/en/me/insured.rb
  spec/helpers/application_helper_spec.rb
Labels: cr-120+

#5429 fix member details page display issues
  components/financial_assistance/app/models/financial_assistance/services/qhp_enabled_raw_applicant.yml.erb
  components/financial_assistance/app/views/financial_assistance/applications/_summary_subsection.html.erb
Labels: cr-120+

#5453 update individual market cv3
  app/domain/operations/eligibilities/v3/individual_market/ssa_vlp_determined.rb
  app/domain/operations/individual_market/transformers/application_to/cv3_application.rb
  spec/domain/operations/individual_market/transformers/application_to/cv3_application_spec.rb
Labels: cr-120+

#5468 populate tribe code on review page and fix view application rediretion issue
  components/financial_assistance/app/models/financial_assistance/applicant.rb
  components/financial_assistance/app/models/financial_assistance/services/qhp_enabled_raw_applicant.yml.erb
  components/financial_assistance/app/views/financial_assistance/applications/_eligibility_results_per_tax_household.html.erb
  components/financial_assistance/spec/models/financial_assistance/applicant_spec.rb
Labels: cr-120+

#5456 ai/an validations, plan shopping text
  app/domain/operations/individual_market/people/create_or_update.rb
  app/javascript/controllers/family_information_controller.js
  app/javascript/css/forms.scss
  app/views/insured/individual_market/applicants/_form.html.erb
  app/views/insured/plan_shoppings/_individual_agreement.en.html.erb
  app/views/insured/plan_shoppings/thankyou.html.erb
  db/seedfiles/translations/en/me/insured.rb
Labels: cr-120+

#5484 homelessness attestation on review page, ssn /no ssn form validation, member details button placement
  app/javascript/controllers/family_information_controller.js
  app/views/insured/individual_market/applicants/_summary.html.erb
Labels: cr-120+

#5486 remove text change from common partial and add it to respective files
  app/views/insured/individual_market/applications/eligibility_results.html.erb
  app/views/shared/_progress_navigation_buttons.html.erb
  components/financial_assistance/app/views/financial_assistance/applications/_eligibility_results_per_tax_household.html.erb
  db/seedfiles/translations/en/me/insured.rb
Labels: cr-120+

#5477 current application links
  app/javascript/controllers/family_information_controller.js
  app/views/insured/individual_market/applications/show.html.erb
  components/financial_assistance/app/views/financial_assistance/applicants/show.html.erb
  components/financial_assistance/app/views/financial_assistance/applications/review.html.erb
  components/financial_assistance/app/views/financial_assistance/applications/show.html.erb
Labels: cr-120+

#5496 add homelessness attestation to FAA review page
  components/financial_assistance/app/models/financial_assistance/services/qhp_enabled_raw_applicant.yml.erb
  components/financial_assistance/app/views/financial_assistance/applications/_summary_subsection.html.erb
Labels: cr-120+
