Repository ideacrew/enroll, pull requests merged in 2025-05, with the labels that each got.

#5194 create/update only primary person and create app with all applicants in ATP inbound process
  app/event_source/subscribers/atp_subscriber.rb
  components/financial_assistance/app/domain/financial_assistance/operations/transfers/medicaid_gateway/v2/account_transfer_in.rb
  components/financial_assistance/app/domain/financial_assistance/operations/transfers/medicaid_gateway/v2/build_family_and_create_member.rb
  components/financial_assistance/spec/domain/financial_assistance/operations/applications/medicaid_gateway/add_eligibility_determination_spec.rb
  components/financial_assistance/spec/domain/financial_assistance/operations/transfers/medicaid_gateway/v2/account_transfer_in_spec.rb
  components/financial_assistance/spec/domain/financial_assistance/operations/transfers/medicaid_gateway/v2/build_family_and_create_member_spec.rb
Labels: cr-120+

#5192 add qhp faa scenarios
  components/financial_assistance/app/views/financial_assistance/applicants/_applicants_info.html.erb
  features/financial_assistance/add_new_member.feature
  features/financial_assistance/step_definitions/applicant_level_navigation_steps.rb
  features/step_definitions/household_info_continue_button_steps.rb
  features/support/object_model_pages/ivl/iap/ivl_iap_family_information.rb
Labels: cr-120+

#5220 disable turbolinks in certain modals
  app/views/insured/families/_shop_for_plans_widget.html.erb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/_broker_help.html.erb
Labels: bug

#5221 disable turbolinks nav to my expert page
  app/views/insured/families/_consumer_brokers_widget.html.erb
Labels: bug

#5219 add script to delete erroneously updated relationships
  app/domain/operations/financial_assistance/delete_invalid_application_relationships.rb
  components/financial_assistance/app/models/financial_assistance/relationship.rb
  components/financial_assistance/spec/models/financial_assistance/relationship_spec.rb
  script/delete_invalid_applicant_relationships.rb
  spec/domain/operations/financial_assistance/delete_invalid_application_relationships_spec.rb
Labels: script

#5228 reset application relationships from csv
  app/domain/operations/financial_assistance/reset_application_relationships_from_csv.rb
  bearer.ignore
  script/reset_application_relationships_from_csv.rb
  spec/domain/operations/financial_assistance/reset_application_relationships_from_csv_spec.rb
Labels: bugfix

#5231 fix wave error on family info page and add missing translation
  app/views/shared/_progress_side_nav.html.erb
  components/financial_assistance/db/seedfiles/translations/en/dc/financial_assistance.rb
  components/financial_assistance/db/seedfiles/translations/en/ic/financial_assistance.rb
  components/financial_assistance/db/seedfiles/translations/en/me/financial_assistance.rb
Labels: cr-120+

#5240 create operation to migrate existing FAA evidence 1.0 to 3.0
  app/domain/operations/async_migrations/handlers/fa_application/migrate_evidence.rb
  app/models/eligibilities/evidence.rb
  app/models/eligibilities/v3/eligibility.rb
  app/models/eligibilities/v3/state_machine.rb
  app/models/has_document.rb
  app/models/migrations/data_model_migrator.rb
  app/models/migrations/mapping_config.yml
  app/models/workflow_state_transition.rb
  components/financial_assistance/app/models/financial_assistance/applicant.rb
  spec/domain/operations/async_migrations/handlers/fa_application/migate_evidence_spec.rb
  spec/models/eligibilities/v3/eligibility_spec.rb
  spec/models/eligibilities/v3/state_machine_spec.rb
  spec/models/migrations/data_model_migrator_spec.rb
Labels: cr-120+

#5254 update eligibility results page content
  components/financial_assistance/app/views/financial_assistance/applications/_eligibility_results_per_tax_household.html.erb
  components/financial_assistance/db/seedfiles/translations/en/dc/financial_assistance.rb
  components/financial_assistance/db/seedfiles/translations/en/ic/financial_assistance.rb
  components/financial_assistance/db/seedfiles/translations/en/me/financial_assistance.rb
Labels: cr-120+
