Repository ideacrew/enroll, pull requests merged in 2025-10, with the labels that each got.

#5748 fix spousal dependent claim validation
  components/financial_assistance/app/models/financial_assistance/applicant.rb
  components/financial_assistance/app/models/financial_assistance/application.rb
  components/financial_assistance/spec/models/financial_assistance/applicant_spec.rb
Labels: bugfix

#5757 upgrade ckeditor to 5.1.3
  .bundler-audit.yml
  Gemfile
  Gemfile.lock
  SECURITY.md
  components/notifier/app/assets/javascripts/notifier/application.js
  components/notifier/app/assets/javascripts/notifier/ckeditor/basepath.js.erb
  components/notifier/notifier.gemspec
Labels: dependencies

#5749 block document deletion if evidence is in verified state
  app/models/eligibilities/v3/evidence_utils.rb
  spec/domain/operations/eligibilities/evidences/documents/delete_spec.rb
  spec/models/eligibilities/v3/evidence_utils_spec.rb
Labels: bugfix, cr-120+

#5742 display application reference dropdown when verifying a document
  app/controllers/eligibilities/evidences/evidences_controller.rb
  app/domain/operations/eligibilities/evidences/show.rb
  app/domain/operations/eligibilities/evidences/update.rb
  app/views/eligibilities/evidences/_admin_actions.html.erb
  db/seedfiles/translations/en/cca/insured.rb
  db/seedfiles/translations/en/dc/insured.rb
  db/seedfiles/translations/en/me/insured.rb
  spec/controllers/eligibilities/evidences/evidences_controller_spec.rb
  spec/domain/operations/eligibilities/evidences/evidences/show_spec.rb
  spec/domain/operations/eligibilities/evidences/update_spec.rb
Labels: enhancement, cr-120+

#5759 use fdsh partials for fdsh views instead of interactive identity
  app/views/insured/fdsh_ridp_verifications/_outstanding_ridp_documents.html.erb
  app/views/insured/fdsh_ridp_verifications/failed_validation.html.erb
Labels: bugfix

#5764 reset due date when evidence is moved to NRR status
  app/models/eligibilities/v3/evidence_utils.rb
  spec/models/eligibilities/v3/evidence_utils_spec.rb
Labels: bugfix, cr-120+

#5775 move inline js to stimulus controller
  app/javascript/controllers/evidence_dropdown_controller.js
  app/views/eligibilities/evidences/_admin_actions.html.erb
Labels: bugfix, cr-120+
